version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: giraffe-postgres
    environment:
      POSTGRES_USER: giraffe
      POSTGRES_PASSWORD: giraffe123
      POSTGRES_DB: giraffe_kitchens
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U giraffe"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: giraffe-app
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - DEBUG=False
      - APP_NAME=Giraffe Kitchens API
      - VERSION=1.0.0
      - DATABASE_URL=postgresql://giraffe:giraffe123@postgres:5432/giraffe_kitchens
      - JWT_SECRET=your-secret-key-change-in-production
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALLOWED_ORIGINS=http://localhost:8000,http://localhost:3000
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
