# fly.toml app configuration file generated for giraffe-backend on 2025-10-18T10:46:07+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'giraffe-backend'
primary_region = 'fra'

[build]

[env]
  DATABASE_URL = "/data/giraffe_kitchens.db"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "giraffe_data"
  destination = "/data"
  initial_size = "1gb"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
