# fly.toml app configuration file for Giraffe Kitchens
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'giraffe-backend'
primary_region = 'fra'

[build]
  dockerfile = "../Dockerfile"
  ignorefile = "../.dockerignore"

[env]
  # Database path (stored in persistent volume)
  DATABASE_URL = "sqlite:////data/giraffe_kitchens.db"

  # Application settings
  APP_NAME = "Giraffe Kitchens API"
  VERSION = "1.0.0"
  DEBUG = "false"

  # CORS settings - update with your production frontend URL
  ALLOWED_ORIGINS = "https://giraffe-backend.fly.dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[mounts]
  source = "giraffe_data"
  destination = "/data"
  initial_size = "1gb"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
