"""Change check_date from DateTime to Date

Revision ID: ac919eceee26
Revises: 675214fd47f2
Create Date: 2025-10-21 17:04:13.983678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac919eceee26'
down_revision = '675214fd47f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # SQLite doesn't support ALTER COLUMN, so we need to use batch operations
    with op.batch_alter_table('dish_checks') as batch_op:
        batch_op.alter_column('check_date',
                   existing_type=sa.DATETIME(),
                   type_=sa.Date(),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_checks') as batch_op:
        batch_op.alter_column('check_date',
                   existing_type=sa.Date(),
                   type_=sa.DATETIME(),
                   existing_nullable=False)
    # ### end Alembic commands ###
