"""Add dish_name_manual and make dish_id nullable

Revision ID: a224016b8261
Revises: 50fb2d55adf0
Create Date: 2025-10-18 21:06:44.789674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a224016b8261'
down_revision = '50fb2d55adf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding them
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Get existing columns
    columns = [col['name'] for col in inspector.get_columns('dish_checks')]

    # Add dish_name_manual only if it doesn't exist
    if 'dish_name_manual' not in columns:
        op.add_column('dish_checks', sa.Column('dish_name_manual', sa.String(), nullable=True))

    # Always try to alter dish_id to be nullable
    op.alter_column('dish_checks', 'dish_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish_checks', 'dish_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('dish_checks', 'dish_name_manual')
    # ### end Alembic commands ###
